export const CURRENCIES = ['INR', 'USD', 'EUR', 'GBP', 'AED', 'JPY', 'KWD'] as const;
export const STATUSES = ['inquiry', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show'] as const;
export const CATEGORIES = ['accommodation', 'rate_adjustment', 'cleaning', 'guest_service_fee', 'host_service_fee', 'tax', 'withholding', 'additional_income', 'discount', 'other'] as const;
export type FinancialLine = {
    side: 'guest' | 'host';
    category: string;
    label: string;
    amount: string;
};
export type BookingRow = {
    id: string;
    reservation_code: string;
    property_id: string;
    property_name: string;
    primary_guest_id: string;
    guest_name: string;
    email: string | null;
    phone: string | null;
    country: string | null;
    unit_label: string | null;
    source: string;
    external_booking_ref: string | null;
    booking_date: string;
    check_in_date: string;
    check_out_date: string;
    nights: number;
    adults: number;
    children: number;
    currency: string;
    status: string;
    financial_status: string;
    collection_mode: 'platform' | 'direct';
    guest_balance: number | null;
    guest_total: number;
    host_total: number;
    guest_received: number;
    host_received: number;
    deposit_held: number;
    payout_balance: number;
    notes: string;
    created_at: string;
    updated_at: string;
    finalized_at: string | null;
};
export type PaymentRow = {
    id: string;
    direction: string;
    amount: number;
    currency: string;
    status: string;
    payment_method: string;
    gateway_reference: string | null;
    account_label: string;
    settled_at: string;
    reversal_reason: string | null;
    created_at: string;
    payment_type: string;
};
export type GuestOption = {
    id: string;
    full_name: string;
    email: string | null;
    phone: string | null;
};
export type PropertyOption = {
  id: string;
  name: string;
  property_type?: 'single_unit' | 'multi_unit';
  default_units?: string[];
};
export type RegisterFilters = Record<string, string | undefined>;
export const SORT_FIELDS = ['check_in_date', 'check_out_date', 'booking_date', 'reservation_code', 'guest_name', 'property_name', 'unit_label', 'source', 'external_booking_ref', 'nights', 'adults', 'children', 'currency', 'status', 'financial_status', 'guest_total', 'host_total', 'guest_received', 'host_received', 'deposit_held', 'payout_balance', 'email', 'phone', 'country', 'created_at','collection_mode','guest_balance'] as const;
